# Generated by Django 2.2.5 on 2021-08-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_auto_20210424_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=264, null=True, unique=True),
        ),
    ]
